# Generated by Django 5.2.5 on 2025-08-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
