# Generated by Django 5.2.5 on 2025-08-19 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemon_description_pokemon_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='title_jp',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='title_ru',
        ),
    ]
