# Generated by Django 5.2.5 on 2025-08-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_remove_pokemon_title_ru_alter_pokemon_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='имя на русском'),
        ),
    ]
