# Generated by Django 5.2.5 on 2025-08-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemon_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title_ru',
        ),
    ]
