# Generated by Django 5.2.5 on 2025-08-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_remove_pokemon_title_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='subject',
            new_name='pokemon_model',
        ),
    ]
